export * as dom from "./dom.js";
export { NS } from "./ns.js";
export { XPath } from "./xpath.js";
export default DomParser;
export type XML_Encoding = import("./domParser.js").XML_Encoding;
export type ReadEntity = import("./domParser.js").ReadEntity;
export type EntityInfo = import("./domParser.js").EntityInfo;
export type ParserOptions = import("./domParser.js").ParserOptions;
export type XPathResult = import("./xpath.js").XPathResult;
import { DomParser } from './domParser.js';
export const xml: typeof DomParser.fromString;
export { DomParser };
