name: Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    branches: ['*']

jobs:
  build:

    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install -r
      - name: Check coding standards
        run: npm run lint
      - name: Unpack conformance tests
        uses: a7ul/tar-action@v1.1.0
        with:
          command: x
          cwd: ./test
          files: ./test/xmlts20130923.tar.gz
          outPath: .
      - name: Test
        run: npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
